version: "3.8"

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ambulance-backend
    restart: unless-stopped
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/ambulance
      - JWT_SECRET=your_jwt_secret # Change in production
    depends_on:
      - db
    networks:
      - ambulance-network

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ambulance-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ambulance-network

  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: ambulance-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ambulance
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - ambulance-network

networks:
  ambulance-network:
    driver: bridge

volumes:
  pgdata:
